### ISSUE TITLE
Content update - Use video-youtube shortcode

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#15]
Update all content in [pupil-docs](https://github.com/pupil-labs/pupil-docs) to use `video-youtube` shortcode. 

Example with a playlist:

```
> {{< video-youtube embed-url="https://www.youtube.com/embed/HGMjJLnK2_4?list=PLi20Yl1k_57r4j0LXDfo6IYXAKTp_FIKf" >}}
```

Example with no playlist:

```
> {{< video-youtube embed-url="https://www.youtube.com/embed/HGMjJLnK2_4" >}}
```

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-docs/pull/8
