### ISSUE TITLE
TOC and hierarchy

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#2]
Move `Pupil Hardware` to top level heading and all setup guides for hardware within this section. 

TOC top level should look like this:

Introduction
Getting Started
Pupil Hardware
User Docs
Developer Docs
Community

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-docs/pull/2
- move getting-started and pupil-hardware to top level
- reorder weight and and added h1's for top level section

**Comment by willpatera** [comment]
refactor complete.
