### ISSUE TITLE
Update styling for "Edit ... on Github"

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#20]
Update css for "edit ... on github"

**Comment by willpatera** [comment]
Make an edit icon and add after the `#` to replace the text.

**Comment by nathakits** [comment]
@willpatera - Should the icon be added dynamically by JS to append the svg?

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/docuapi/pull/12

**Comment by willpatera** [comment]
Done - closing. Used material icon font.
