### ISSUE TITLE
Use the same mouse cursor for links and buttons

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil-docs-website#21]
Just an observation.

![screenshot - 03272017 - 06 33 41 pm](https://cloud.githubusercontent.com/assets/6511849/24379248/9c106cd8-131c-11e7-8378-7addab947915.png)

![screenshot - 03272017 - 06 34 35 pm](https://cloud.githubusercontent.com/assets/6511849/24379249/9c18d2b0-131c-11e7-8cf0-8ae372f9dc4b.png)

**Comment by willpatera** [comment]
@cpicanco thanks - this will be fixed soon 😄

**Comment by willpatera** [comment]
@nathakits - please check for consistency and fix if needed.

**Comment by willpatera** [comment]
@nathakits - what is the status with this issue?

**Comment by nathakits** [comment]
I do not see this inconsistency. Maybe it only happened with the previous `edit` link.

**Comment by willpatera** [comment]
@nathakits related to #41

**Comment by cpicanco** [comment]
Error persists on Firefox 45.9.0.

**Comment by willpatera** [comment]
@nathakits - still not fixed for edit and anchor links. 

`cursor: pointer` needs to be specified.

**Comment by willpatera** [comment]
This should be fixed now with the recent PR.
