### ISSUE TITLE
Image Performance - Lazyload Images

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#27]
lazyload images in pupil docs website - http://afarkas.github.io/lazysizes/

**Comment by willpatera** [comment]
See #26

**Comment by nathakits** [comment]
@willpatera  Lazyload PR's
Imagemin gulptask PR - https://github.com/pupil-labs/pupil-docs-website/pull/31
update images to lqip shortcodes in markdown PR - https://github.com/pupil-labs/pupil-docs/pulls
add new and update existing scss for lazyload images PR - https://github.com/pupil-labs/docuapi/pull/14

**Comment by nathakits** [comment]
@willpatera - pushed the changes to the PR's

**Comment by willpatera** [comment]
done - closing.
