### ISSUE TITLE
Image Performance - Use webp with jpg fallback

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#28]
Use webp format with jpeg fallback

Use an html5 [`<picture>`](https://www.html5rocks.com/en/tutorials/responsive/picture-element/) element with webp and jpg for fallback on [browsers that do not support webp](http://caniuse.com/#feat=webp)
```
<picture>
  <source srcset="/images/example.webp" type="image/webp">
  <source srcset="/images/example.jpg" type="image/jpeg"> 
  <img src="/images/example.jpg" alt="Image alt txt">
</picture>
```
Make a shortcode for :point_up: so that users can just write something like {< img src="/images/example.jpg" >} and the shortcode can be smart enough to decide how to set up the markup.

**Comment by willpatera** [comment]
See #26

**Comment by willpatera** [comment]
Closing - with proper image optimization and lqip this is not a urgent requirement.
