### ISSUE TITLE
webm video loader with mov/mp4 fallback

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#32]
Make webm video loader with mov/mp4 fallback for browsers that do not support webm

**Comment by nathakits** [comment]
using this video library for video player - https://github.com/Selz/plyr

**Comment by nathakits** [comment]
@willpatera - PR's
plyr js build task - https://github.com/pupil-labs/pupil-docs-website/pull/38
plyr js script / scss / shortcode / js partial  - https://github.com/pupil-labs/docuapi/pull/17

the only thing todo next is to make the `webm/mp4` videos with` img-placeholders` and add them to the content `.md`

**Comment by nathakits** [comment]
Keyboard shortcuts - https://github.com/Selz/plyr/blob/master/readme.md#shortcuts

**Comment by nathakits** [comment]
@willpatera - Updated and new PR's for webm
plyr js build task - https://github.com/pupil-labs/pupil-docs-website/pull/38
plyr js script / scss / shortcode / js partial - https://github.com/pupil-labs/docuapi/pull/17
-webm videos and img placeholders - https://github.com/pupil-labs/pupil-docs/pull/35

copytext still needs work

**Comment by nathakits** [comment]
Merged to master
