### ISSUE TITLE
Fix media breakpoints

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#33]
Media breakpoints should be as follow:

mobile: size < 768
  - collapse navbar
  - single column layout
 
desktop/laptop: size > 768
  - show navbar
  - two column layout

optional image breakpoint: size < 1024
  - scale figure container (?) this needs testing

**Comment by nathakits** [comment]
@willpatera  PR - 
update scss to fix breakpoint and scale images properly - https://github.com/pupil-labs/docuapi/pull/15
add classes to scale images properly - https://github.com/pupil-labs/pupil-docs/pull/21

**Comment by willpatera** [comment]
Closed with https://travis-ci.org/pupil-labs/pupil-docs-website/builds/220978107
