### ISSUE TITLE
Quick nav links offset

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#37]
Currently the quick nav jumps to links with no offset from the fixed header. Todo - add offset like TOC and anchor links

**Comment by willpatera** [comment]
Define "quick nav".

**Comment by nathakits** [comment]
The navigation links in the introduction section. 
![screenshot 2017-04-12 16 20 40](https://cloud.githubusercontent.com/assets/17331040/24950692/0e90f4c2-1f9c-11e7-8cb3-c7c97e1fed8f.png)

**Comment by nathakits** [comment]
@willpatera - this still needs to be fixed.
