### ISSUE TITLE
Firefox - Incorrect cursor icon for anchor and edit links

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#41]
Change cursor icon for anchor and edit links to the correct cursor

**Comment by willpatera** [comment]
@nathakits - has this been resolved?

**Comment by willpatera** [comment]
@nathakits - please work on this issue it is a .css issue for the cursor.

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/docuapi/pull/25

@willpatera - please review PR

**Comment by willpatera** [comment]
This should be fixed with the PR above - merged.
