### ISSUE TITLE
Performance - Webp

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#43]
Create .webp shortcode with .jpg fallback inside <picture> tag, similar to the webm and lqip shortcodes.

**Comment by nathakits** [comment]
https://github.com/pupil-labs/docuapi/pull/20
https://github.com/pupil-labs/pupil-docs/pull/48
https://github.com/pupil-labs/pupil-docs-website/pull/42

**Comment by nathakits** [comment]
PR for webp images - https://github.com/pupil-labs/pupil-docs/pull/54

**Comment by willpatera** [comment]
done.
