### ISSUE TITLE
Bad contrast between link green and info box blue

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs-website#47]
See screenshot ![screenshot from 2017-05-30 10-50-59](https://cloud.githubusercontent.com/assets/168390/26575556/0a55757c-4526-11e7-8821-db04f77ef8c6.png)

**Comment by papr** [comment]
I wonder if a light color (e.g. white) would work better.

**Comment by willpatera** [comment]
@nathakits please work on this issue.

**Comment by nathakits** [comment]
![aside-color](https://cloud.githubusercontent.com/assets/17331040/26710324/3880b51a-4783-11e7-9f62-f7473b3d569d.png)

Side by side color comparison between all the aside tags. Updated the background color and the link text for each tags.

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/docuapi/pull/24

@willpatera - please review this PR

**Comment by willpatera** [comment]
@nathakits - I think `warn` should be more orange-red than yellow.

**Comment by papr** [comment]
I like the new background colors. But I still feel that the link color is not quite fitting. My suggestion was a lighter link color previously, but the new background colors are much more vivid / have more saturation. I think that the contrast between link and text is not as important as between link and background.

I still need to see the screenshot on a bigger screen than my phone though.

**Comment by nathakits** [comment]
@papr - thanks for the input. I actually based the color contrasts for both the link and the text and the background colors all together. I think they are equally important to account for all the color contrasts between all the elements. 

After some consideration, discussions and more tests. The goal here is to limit the use of too much colors. And so to keep these aside tags integrated more with the whole theme, i decided to use the colors on the left border and the icons only. With the links being all the same color for the whole site

I also added some margin to the aside tags to have the same spacing as all the content

![screenshot 2017-06-05 16 22 57](https://cloud.githubusercontent.com/assets/17331040/26778389/45c0ee86-4a0b-11e7-9131-a5c7d435898a.png)

updated  PR - https://github.com/pupil-labs/docuapi/pull/24

**Comment by papr** [comment]
I think that this is a very good solution. Great work!

**Comment by nathakits** [comment]
@papr @willpatera  - Right now the aside tags are done. I am now working on the links to improve contrast and legibility, by updating the color of the links to cyan. But for more contrast should we consider underlining the links?

![screenshot 2017-06-05 17 05 18](https://cloud.githubusercontent.com/assets/17331040/26779869/59188b78-4a11-11e7-9ca0-8b69107702ef.png)
![screenshot 2017-06-05 17 05 07](https://cloud.githubusercontent.com/assets/17331040/26779878/5bb1a0ea-4a11-11e7-9409-c0e1d7dba13c.png)

**Comment by willpatera** [comment]
@nathakits IMO I would opt not to have underline. @papr thoughts?

**Comment by papr** [comment]
I would use either colored links without underline or uncolored links with underline. 

In case the underline would be used, I would recommend implementing it with the text-style css attribute instead of border-bottom. This way one gets less control over thickness etc, but the line would be closer to the text and have spaces for the letters p, q, g, y, and j

**Comment by willpatera** [comment]
@nathakits let's do no underline and just colored text.

**Comment by nathakits** [comment]
I think we could just go with the one without the underline.
