### ISSUE TITLE
Implement service worker

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#52]
Implement service worker to speed up load times and offline performance.

**Comment by nathakits** [comment]
PR 
service worker gulptask - https://github.com/pupil-labs/pupil-docs-website/pull/63
service worker js script - https://github.com/pupil-labs/docuapi/pull/31

@willpatera - please review PR. This still needs more testing and could be improved more.

**Comment by willpatera** [comment]
This has been merged. Needs testing on Safari and mobile.

**Comment by nathakits** [comment]
Update old SW PR - 

updated build and caching tasks - https://github.com/pupil-labs/pupil-docs-website/pull/81
service worker script to register for each tag / minor update master pupil sw js file - https://github.com/pupil-labs/docuapi/pull/37

Note - if it fails to register or install, the reason would be that some media assets are missing and thus the SW cannot register.

@willpatera - please review PR.
