### ISSUE TITLE
Failing to load page on Chrome v59

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs-website#53]
After setting up the new NUC I ran into the following issue when opening `docs.pupil-labs.com`:
![image](https://cloud.githubusercontent.com/assets/168390/26834293/3826e35a-4ad5-11e7-8bde-24e0b451d639.png)

Just reloading does not fix the problem at all. Clearing the browser cache fixes the problem sometimes but not consistently and the problem reappears when opening when opening a new tab.

Google Chrome `Version 59.0.3071.86 (Official Build) (64-bit)`

**Comment by willpatera** [comment]
@papr I can not replicate this issue with any browser or any chrome version from v58 to v61 (canary).

**Comment by papr** [comment]
Ubuntu 16.04. I am not exactly sure what happened to the title there 🙈

**Comment by willpatera** [comment]
@papr - same OS here and same chrome version. Not able to replicate your issues :crying_cat_face:

**Comment by papr** [comment]
What is also funny is that it showed the page for some seconds and then switched to the Aw Snap mode. It really looks like something crashed inside Chrome there. 

Tomorrow I will check if not using i3 as a window manager makes a difference.

**Comment by willpatera** [comment]
@papr - please do check to see if this is i3 related. Because we have tested here with similar hardware, and the same software and can not replicate.

**Comment by papr** [comment]
Do you know a way to access a crash report or something similar within Chrome to debug the issue?

**Comment by papr** [comment]
I cannot reproduce the issue right now. I will close it and reopen in case that it reappears.
