### ISSUE TITLE
Make custom image check for HTML proofer

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#57]
Build the site locally to debug and fix images with missing srcset attributes. Working only on master branch.
Missing srcset attributes (this one is a bit tricky because it may be set dynamically with .js lazyloading)

**Comment by nathakits** [comment]
Changing the issue to make custom image check to not check missing src or srcset attributes instead. The reason is to keep using the lazysizes shortcode as is and have the HTML proofer not check for missing src and srcset attribute for images.

**Comment by nathakits** [comment]
PR - HTMLproofer custom check - https://github.com/pupil-labs/pupil-docs-website/pull/62

**Comment by willpatera** [comment]
Done, merged.
