### ISSUE TITLE
Change inline <code> word-break behaviour

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs-website#61]
Current css `.content code` is set to `word-break: break-all`. Should be changed to `break-word` for inline code blocks.

Screenshot how it looks currently:
![image](https://user-images.githubusercontent.com/168390/26971065-07405404-4d0c-11e7-8d3f-6d1ff5350659.png)

**Comment by nathakits** [comment]
PR - break-word - https://github.com/pupil-labs/docuapi/pull/30

**Comment by willpatera** [comment]
Merged. Requires review on master site after build.
