### ISSUE TITLE
Webm shortcode with webp poster images

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#68]
Currently the webm shortcode poster image is serving only jpg files. The aim is to load webp as default and swap jpg files when the browser doesn't support webp.

Task - create a browser support check for webp images. If true then load the webp poster images but if false then load the jpgs.

**Comment by nathakits** [comment]
PR - 
webp gulptask and add modernizr to js build task - https://github.com/pupil-labs/pupil-docs-website/pull/69
add webp poster images  - https://github.com/pupil-labs/pupil-docs/pull/63
modernizr webp js / webp check js / webm shortcode update - https://github.com/pupil-labs/docuapi/pull/33

@willpatera - please review PR

**Comment by willpatera** [comment]
Merged!
