### ISSUE TITLE
Lazyload youtube videos

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#72]
lazyload embedded youtube videos. By embedding videos we request more than just a video file. A number of resources are fetched. So, instead of loading the Youtube video as soon as the page loads, we are going to pull and play the video when the user asks to do so.

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-docs-website/pull/71

**Comment by willpatera** [comment]
Merged! Much better performance 😄
