### ISSUE TITLE
Markdown within aside blocks is not rendered correctly

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs-website#75]
![image](https://user-images.githubusercontent.com/168390/27435212-b7e9c78c-575b-11e7-9e07-51933d993805.png)

I am aware that this is probably not easy to fix since the markdown parser will parse the complete `aside` block as `html` and will not look within it for `markdown`. Similar issues might arise if one wants to use enumerations within the aside block. It is questionable if the effort to fix this issue is worth it since it only appears in aside notes.

A work-around is to write proper html within the aside block.

**Comment by nathakits** [comment]
This is expected behavior according to Markdown spec:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style emphasis inside an HTML block.

Currently blackfriday markdown (markdown we are using) does not support markdown parsing in HTML. So for the time being i think just write proper html within the aside blocks.

Reference: https://github.com/russross/blackfriday/issues/184
