### ISSUE TITLE
Update Print css

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#87]
Update the css print style so that when a reader pressed cmd + p they will be able to see proper docs layout. This should print the mobile layout where videos and images are inline - not in the sidebar. And the TOC should either not exist or be the first page of the document.

**Comment by nathakits** [comment]
@willpatera - work in progress PR https://github.com/pupil-labs/docuapi/pull/38

Note - there are still some text breaks on some pages which i am having difficulty debugging

**Comment by willpatera** [comment]
Merged https://github.com/pupil-labs/docuapi/pull/38
