### ISSUE TITLE
"Whats new" section

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs-website#89]
There is a lot of new content on Pupil docs. This includes changes of out-of-date docs. To keep track one could subscribe to the repository's PRs but Github only renderes the markdown part, not images and videos. I would like to have a "what is new" section which simply lists the links to all changed topics for each Pupil docs release. This way, our users could keep up improving their knowledge about the products. Especially in those parts that are refactored/rewritten.
This could even be automated by the having access to PR changes via the github api and creating such a list of changed headlines automatically by the renderer.

**Comment by willpatera** [comment]
We have decided not to implement this feature.
