### ISSUE TITLE
Add documentation for html proofer

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#90]
add description and documentation about html proofer script 
- description -> test rendered html files for errors
- link -> https://github.com/gjtorikian/html-proofer
- docs -> Installing ruby (macos / debian / windows).

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs-website/pull/92

**Comment by willpatera** [comment]
Merged; closing :smile:
